apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: devsecops
spec:
  selector:
    app: auth-service
  ports:
    - name: http
      port: 3001
      targetPort: 3001
    - name: metrics
      port: 9101
      targetPort: 9101
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: pikafoc/skanderdevsopp-auth-service
          ports:
            - containerPort: 3001
            - containerPort: 9101
          env:
            - name: OTEL_SERVICE_NAME
              value: auth-service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger.devsecops.svc.cluster.local:4318
            - name: METRICS_PORT
              value: "9101"
          envFrom:
            - configMapRef:
                name: devsecops-config
            - secretRef:
                name: service-secrets
