apiVersion: v1
kind: Secret
metadata:
  name: service-secrets
  namespace: devsecops
type: Opaque
stringData:
  DATABASE_URL: postgresql://user:password@postgres:5432/devsecops
  RABBITMQ_URL: amqp://user:password@rabbitmq:5672
  MONGODB_URI: mongodb://admin:password@mongodb:27017/monitor_db?authSource=admin
  JWT_SECRET: your-secret-key-change-in-production
