global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['api-gateway.devsecops.svc.cluster.local:5000']

  - job_name: 'auth-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth-service.devsecops.svc.cluster.local:9101']

  - job_name: 'infrastructure-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['infrastructure-service.devsecops.svc.cluster.local:9102']

  - job_name: 'agents-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['agents-service.devsecops.svc.cluster.local:9103']

  - job_name: 'monitor-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['monitor-service.devsecops.svc.cluster.local:9104']
